version: '3'

services:
  postgresql:
    build: ./data
    container_name: pg-docker
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - /var/data/
      - /var/storage:/var/lib/postgresql/data
    restart: always
  
  api:
    build: ./server
    container_name: api-docker
    command: pm2-runtime ecosystem.config.js 
    ports:
      - "3333:3333"
    depends_on:
      - postgresql
    environment:
      - DB_HOST=postgresql
      - DB_NAME=reviews
      - DB_PORT=5432
      - DB_USER=docker
      - DB_PASSWORD=docker
    volumes:
      - /usr/src/reviews/server