version: '3'

services:
  postgresql:
    image: postgres
    container_name: pg-docker
    expose:
      - "5400"
    ports:
      - "5400:5400"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./data/postgres.conf:/etc/postgresql/postgresql.conf
      - ./data:/var/data
      - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./data/seed.sh:/docker-entrypoint-initdb.d/seed.sh
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
  
  api:
    build: .
    container_name: api-docker
    command: node app.js --port 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
    environment:
      - DB_HOST=postgresql
      - DB_NAME=reviews
      - DB_PORT=5400
      - DB_USER=docker
      - DB_PASSWORD=docker
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
